##
## Hello World Action
##

# name: JS Actions

# # Controls when the action will run. 
# on: [push]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   action:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
        
#       - name: hello-action
#         uses: ./.github/actions/hello-world
#         with:
#           first-greeting: "Learning Lab User"
#           second-greeting: "GitHub Action"
#           third-greeting: "JavaScript Action"
